import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { VERBS } from "../manifest/types.js";
import { gatherSkillContext, type SkillContext } from "./skill.js";

// The discovery tier (DESIGN §3/§7, companion to the skill tier): once a repo is
// adopted, coding agents working in it should reach for premo verbs instead of
// re-deriving bespoke commands — but they only will if they're *told*, in a place
// that's always in context. So `premo adopt` plants a short, managed pointer block
// in AGENTS.md (the cross-tool agent-instructions standard premo itself uses), and
// the full manual is generated on demand by `premo guide`. Two lifetimes, two
// homes: the always-loaded reflex vs. the on-demand reference.

export const AGENTS_FILE = "AGENTS.md";
export const CLAUDE_FILE = "CLAUDE.md";

// Marker pair delimiting premo's managed region. The start marker carries a prose
// warning so a human editing AGENTS.md by hand knows not to touch the inside.
const START = "<!-- premo:start";
const START_LINE = `${START} (generated by \`premo adopt\` — edits between these markers are overwritten) -->`;
const END = "<!-- premo:end -->";

// Replace premo's managed block in `existing`, or append it if absent. Pure and
// idempotent: feeding back its own output is byte-for-byte stable, so a re-adopt
// with no detected changes writes nothing. The `block` argument is the full region
// *including* both markers and carries no trailing newline.
export function upsertManagedBlock(existing: string, block: string): string {
  const startIdx = existing.indexOf(START);
  if (startIdx === -1) {
    // Append after the user's prose, separated by a blank line; brand-new files
    // get just the block. Either way the result ends in a single trailing newline.
    const base = existing === "" ? "" : existing.replace(/\n*$/, "\n\n");
    return `${base}${block}\n`;
  }
  const endMarkerIdx = existing.indexOf(END, startIdx);
  if (endMarkerIdx === -1) {
    // Start marker but no end (someone truncated the file): replace from the start
    // marker to EOF rather than nesting a second block.
    return `${existing.slice(0, startIdx)}${block}\n`;
  }
  return existing.slice(0, startIdx) + block + existing.slice(endMarkerIdx + END.length);
}

// The always-in-context block: the few facts an agent needs *before* it acts —
// that premo owns the verbs here, what they resolve to, and where to go for more.
// Kept in Prettier's markdown normal form (list not table, `_` emphasis,
// single-line bullets) so it never trips the lint step in an adopted repo.
export function renderAgentsBlock(ctx: SkillContext): string {
  const verbList =
    ctx.wired.length > 0
      ? ctx.wired.map((w) => `- \`premo ${w.verb}\` → \`${w.command}\``).join("\n")
      : "- _verbs not wired yet — run `premo skill` to finish setup_";

  const unwiredNote =
    ctx.unwired.length > 0 && ctx.wired.length > 0
      ? `\n\nNot yet wired: ${ctx.unwired.map((v) => `\`${v}\``).join(", ")} (run \`premo skill\` to map them).`
      : "";

  return `${START_LINE}

## 🛠️ This repo is managed by [premo](https://github.com/drewag/premo)

premo gives every project the **same five verbs**. Use them instead of raw build/run/test commands — they are the source of truth for how _this_ repo works, and they keep agent and human muscle memory identical across repos.

Verbs wired for this repo:

${verbList}${unwiredNote}

- **Before** adding a package, directory, or build step, run **\`premo adopt\`** — it re-detects the stack and merges into \`premo.json\` additively, never clobbering your edits.
- For anything else about premo (flags, monorepos, ports, env, deploy, background dev, native/Xcode), run **\`premo guide\`** for the full reference.
- Machine-readable status is **\`premo doctor --json\`**; resolved commands live in \`premo.json\`.

${END}`;
}

export interface AgentsDocResult {
  agentsPath: string;
  agentsChanged: boolean; // the managed block was written (created or updated)
  claudeCreated: string | null; // path to a CLAUDE.md we created, else null
}

// Plant/refresh the discovery block. Self-gating: writes AGENTS.md only when the
// block actually differs, so it's safe to call on every adopt/sync. Reads the
// just-written premo.json off disk (via gatherSkillContext) so the block reflects
// the freshest resolved verbs.
export async function ensureAgentsDoc(root: string): Promise<AgentsDocResult> {
  const ctx = await gatherSkillContext(root);
  const block = renderAgentsBlock(ctx);

  const agentsPath = path.join(root, AGENTS_FILE);
  const existing = existsSync(agentsPath) ? await readFile(agentsPath, "utf8") : "";
  const next = upsertManagedBlock(existing, block);
  const agentsChanged = next !== existing;
  if (agentsChanged) await writeFile(agentsPath, next, "utf8");

  // Claude Code reliably auto-loads CLAUDE.md; AGENTS.md is honored by Cursor,
  // Codex, and others. If there's no CLAUDE.md, drop a one-line @-import so the
  // `claude` CLI discovers the block too. Never touch an existing CLAUDE.md — the
  // user (or another tool) owns it, and may already import AGENTS.md their own way.
  const claudePath = path.join(root, CLAUDE_FILE);
  let claudeCreated: string | null = null;
  if (!existsSync(claudePath)) {
    await writeFile(claudePath, "@AGENTS.md\n", "utf8");
    claudeCreated = claudePath;
  }

  return { agentsPath, agentsChanged, claudeCreated };
}

// The on-demand manual emitted by `premo guide`: the full premo vocabulary plus
// this repo's resolved state. Generated from the installed binary so it can never
// drift from the version actually running, and nothing large is committed per-repo.
export function renderGuide(ctx: SkillContext): string {
  const verbList = "`" + VERBS.join("` · `") + "`";
  const wiredLines =
    ctx.wired.length > 0
      ? ctx.wired.map((w) => `- \`premo ${w.verb}\` → \`${w.command}\``).join("\n")
      : "- _none resolved yet — run `premo skill` and follow the generated task file_";
  const unwiredLines =
    ctx.unwired.length > 0 ? ctx.unwired.map((v) => `\`${v}\``).join(", ") : "_none — all wired_";

  return `# premo — agent guide for \`${ctx.name}\`

premo is a universal task runner: one fixed, closed vocabulary that means the same
thing in every repo, whether premo scaffolded it or just adopted it. Reach for a
premo verb before writing a bespoke command — that's the whole point of it.

## The five verbs

${verbList} — never invent new ones. Project-specific entry points are \`shells\`,
not verbs.

| Verb     | Contract                                                              |
| -------- | -------------------------------------------------------------------- |
| \`dev\`    | Run locally in the foreground (watch mode if it has one).            |
| \`build\`  | Produce the build artifact(s) for what changed.                     |
| \`test\`   | Run the test suite for what changed.                                |
| \`lint\`   | Lint **and auto-fix** in place (\`--dry\` checks only).               |
| \`deploy\` | Ship what changed (often unset until there's a real deploy path).   |

\`dev\`/\`build\`/\`test\` operate on the *affected* targets by default. Run
\`premo dev --background\` to detach (then \`premo stop\` / \`premo logs\`).

## Resolved for this repo

- **Name:** \`${ctx.name}\`  •  **Adapter:** ${ctx.adapter ?? "none matched"}  •  **Root:** \`${ctx.root}\`

${wiredLines}

Unwired verbs: ${unwiredLines}

## Utility commands

- \`premo adopt\` — detect the stack and write/merge \`premo.json\`. Additive by
  default (re-run after adding a package, dir, or build step); \`--force\` rewrites.
- \`premo doctor [--json]\` — diagnose what's wired without side effects.
- \`premo stop\` / \`premo logs\` / \`premo ports\` — manage \`dev --background\` sessions.
- \`premo data <create|clone|delete|list>\` — isolated data instances
  (when \`data\` is wired): each gets its own state; run one with \`premo dev --data <handle>\`.
- \`premo open\` — open the project's URL in the browser (\`openUrl\`/\`$PORT\`).
  \`premo shell\` — enter a configured shell. \`premo share\` — expose a dev port publicly.
- \`premo skill\` — when a repo is only partly wired, emit a \`SKILL.md\` task file
  that walks an agent through finishing \`premo.json\`.

## Working in a premo repo

- **Don't** run the underlying tool directly (\`yarn build\`, \`xcodebuild\`, …) when
  a verb exists — use the verb so behavior stays uniform.
- **After** adding a package/target/env, run \`premo adopt\` so \`premo.json\` and
  port allocations stay in sync. Your hand edits to \`premo.json\` always win on a
  re-adopt; detection only fills gaps and appends.
- HTTP dev servers bind \`$PORT\` (premo allocates a conflict-free block per repo).
- Everything premo knows lives in \`premo.json\`; \`--json\` modes give you
  machine-readable output to parse directly.

See DESIGN.md / CONTRIBUTING.md in the premo repo for the convention → configure →
skill tiering and how repo-specific wiring graduates into a built-in adapter.
`;
}
