import YAML from "yaml";
import { StrandManifest } from "../strand-api/types.js";
import type { PortAllocation } from "./ports.js";

export interface ComposeOptions {
  projectName: string;
  strands: StrandManifest[];
  ports: PortAllocation;
  dataDir: string;
}

export function generateCompose(opts: ComposeOptions): string {
  const services: Record<string, unknown> = {};
  const volumes: Record<string, unknown> = {};

  for (const strand of opts.strands) {
    if (!strand.compose) continue;
    for (const [name, def] of Object.entries(strand.compose.services ?? {})) {
      if (services[name]) {
        throw new Error(`Compose service "${name}" defined by multiple strands. Rename one.`);
      }
      services[name] = def;
    }
    for (const [name, def] of Object.entries(strand.compose.volumes ?? {})) {
      volumes[name] = def;
    }
  }

  const doc: Record<string, unknown> = {
    name: opts.projectName,
    services,
  };
  if (Object.keys(volumes).length > 0) doc.volumes = volumes;

  return [
    "# Generated by strand. Do not edit; re-run `strand sync` to refresh.",
    `# Project: ${opts.projectName}`,
    YAML.stringify(doc),
  ].join("\n");
}

export function composeEnv(
  opts: Pick<ComposeOptions, "projectName" | "ports" | "dataDir">,
): Record<string, string> {
  return {
    COMPOSE_PROJECT_NAME: opts.projectName,
    STRAND_DATA_DIR: opts.dataDir,
    ...Object.fromEntries(Object.entries(opts.ports).map(([k, v]) => [k, String(v)])),
  };
}
